name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Build executable
        shell: powershell
        run: |
          sh bin/deploy-windows.sh
          sh bin/deploy-macos.sh
          sh bin/deploy-linux.sh
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "CHANGELOG.md"
          allowUpdates: true
          removeArtifacts: true
